trigger:
- master 

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  azureSubscription: 'testServiceConnection' 
  appName: 'app-billing-dev-021' 
  publishDirectory: '$(Build.ArtifactStagingDirectory)/publish'

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '8.0.x'  

    - task: NuGetToolInstaller@1

    - task: NuGetCommand@2
      inputs:
        restoreSolution: '**/*.sln'

    # Use VSBuild to build the project (without packaging)
    - task: VSBuild@1
      inputs:
        solution: '**/*.sln'
        platform: 'Any CPU'
        configuration: '$(buildConfiguration)'

    # Publish the project to a folder
    - task: VSBuild@1
      inputs:
        solution: '**/*.sln'
        msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PublishUrl=$(publishDirectory) /p:Configuration=$(buildConfiguration)'
        platform: 'Any CPU'
        configuration: '$(buildConfiguration)'

    # Publish the folder as artifact
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(publishDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'

- stage: Deploy
  dependsOn: Build
  jobs:
  - deployment: DeployWebApp
    environment: 'production'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadBuildArtifacts@0
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'drop'
              downloadPath: '$(System.ArtifactsDirectory)'

          - task: AzureWebApp@1
            inputs:
              azureSubscription: '$(azureSubscription)'
              appType: 'webApp'
              appName: '$(appName)'
              package: '$(System.ArtifactsDirectory)/drop/**'    # Deploy the published folder, not a zip


# trigger:
# - master 

# pool:
#   vmImage: 'windows-latest'

# variables:
#   buildConfiguration: 'Release'
#   azureSubscription: 'testServiceConnection' 
#   appName: 'app-billing-dev-021' 
#   publishDirectory: '$(Build.ArtifactStagingDirectory)/publish'

# stages:
# - stage: Build
#   jobs:
#   - job: Build
#     steps:
#     - task: UseDotNet@2
#       inputs:
#         packageType: 'sdk'
#         version: '8.0.x'  

#     - task: NuGetToolInstaller@1

#     - task: NuGetCommand@2
#       inputs:
#         restoreSolution: '**/*.sln'

#     - task: VSBuild@1
#       inputs:
#         solution: '**/*.sln'
#         msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(publishDirectory)"'
#         platform: 'Any CPU'
#         configuration: '$(buildConfiguration)'

#     - task: PublishBuildArtifacts@1
#       inputs:
#         PathtoPublish: '$(publishDirectory)'
#         ArtifactName: 'drop'
#         publishLocation: 'Container'

# - stage: Deploy
#   dependsOn: Build
#   jobs:
#   - deployment: DeployWebApp
#     environment: 'production'
#     strategy:
#       runOnce:
#         deploy:
#           steps:
#           - task: DownloadBuildArtifacts@0
#             inputs:
#               buildType: 'current'
#               downloadType: 'single'
#               artifactName: 'drop'
#               downloadPath: '$(System.ArtifactsDirectory)'

#           - task: AzureWebApp@1
#             inputs:
#               azureSubscription: '$(azureSubscription)'
#               appType: 'webApp'
#               appName: '$(appName)'
#               package: '$(System.ArtifactsDirectory)/drop/**/*.zip'
